version: '3.2'

services:
  db:
    image: postgres:12.2-alpine
    container_name: temp_db
    ports:
      - 5432:5432
    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: temp_db
      POSTGRES_USER: temp_db
      POSTGRES_PASSWORD: temp_db
    volumes:
      - ./.db_data/postgres:/var/lib/postgresql/data
      - ./.db_data/dump/:/docker-entryporint-initdb.d/